### ISSUE TITLE
CGPathRef memory leak in DJBezierPath

### ISSUE THREAD

**Issue by Phisto** [danielmj/DJProgressHUD_OSX#4]
The Analyser indicate and Instruments shows a memory leak.
One need to call CGPathRelease() at some point. 

I call it in the method 
[DJProgressIndicator createRingLayerWithCenter:radius:lineWidth:color:].
Than everyting is fine :+1:

**Comment by danielmj** [comment]
Awesome! Ty, I will get this updated
